package eu.mshade.enderframe.inventory;

public enum ClickType {

    CONTROL_DROP,
    CREATIVE,
    DOUBLE_CLICK,
    DROP,
    LEFT,
    MIDDLE,
    NUMBER_KEY,
    RIGHT,
    SHIFT_LEFT,
    SHIFT_RIGHT,
    UNKNOWN,
    WINDOW_BORDER_LEFT,
    WINDOW_BORDER_RIGHT,
    START_DRAG_LEFT,
    END_DRAG_LEFT,
    START_DRAG_RIGHT,
    END_DRAG_RIGHT,
    START_DRAG_MIDDLE,
    END_DRAG_MIDDLE,
    ADD_ITEM_FROM_DRAG;

}
